import difflib
import html
import json
import os

from pipeline import normalize_minutes

DEL_STYLE = ("background-color:#ffcdd2;text-decoration:line-through;padding:2px 4px;"
             "margin:0 2px;border-radius:3px;color:#b71c1c;font-weight:600;")
INS_STYLE = ("background-color:#c8e6c9;text-decoration:none;padding:2px 4px;"
             "margin:0 2px;border-radius:3px;color:#1b5e20;font-weight:600;")


def generate_diff_html(raw_text, refined_text):
    """Word-level comparison: red = removed from the raw text, green = added by refinement."""
    raw_words, refined_words = raw_text.split(), refined_text.split()
    matcher = difflib.SequenceMatcher(None, raw_words, refined_words, autojunk=False)
    output = []

    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        if tag == "equal":
            output.append(html.escape(" ".join(raw_words[i1:i2])))
            continue
        if tag in ("replace", "delete"):
            output.append(f'<del style="{DEL_STYLE}">{html.escape(" ".join(raw_words[i1:i2]))}</del>')
        if tag in ("replace", "insert"):
            output.append(f'<ins style="{INS_STYLE}">{html.escape(" ".join(refined_words[j1:j2]))}</ins>')

    body = " ".join(output) if output else "(empty)"
    return ('<div style="line-height:1.8;font-family:sans-serif;font-size:16px;padding:12px;'
            f'border:1px solid #c0c0c0;border-radius:6px;">{body}</div>')


def build_markdown_report(data):
    """Human-readable meeting record. Contains the same decisions and tasks as the JSON."""
    md = ["# Meeting Record", ""]
    md += ["## Summary", data.get("summary") or "No summary generated.", ""]

    md.append("## Minutes")
    minutes = normalize_minutes(data.get("minutes"))
    if not minutes:
        md.append("_No minutes generated._")
    for topic in minutes:
        md.append(f"### {topic['topic']}")
        md += [f"- {point}" for point in topic["points"]]
    md.append("")

    md.append("## Key Decisions")
    decisions = data.get("decisions") or []
    if not decisions:
        md.append("_No decisions were clearly agreed in the recording._")
    for number, d in enumerate(decisions, start=1):
        md.append(f"{number}. **{d.get('decision')}**")
        flag = "verified in transcript" if d.get("verified_in_transcript") else "NOT found in transcript - check"
        md.append(f"   - Evidence: \"{d.get('quote')}\" ({flag})")
    md.append("")

    md.append("## Action Items")
    actions = data.get("action_items") or []
    if not actions:
        md.append("_No action items were assigned in the recording._")
    for number, a in enumerate(actions, start=1):
        md.append(f"{number}. **{a.get('task')}**")
        md.append(f"   - Owner: {a.get('owner', 'unspecified')}")
        md.append(f"   - Deadline: {a.get('deadline', 'unspecified')}")
        flag = "verified in transcript" if a.get("verified_in_transcript") else "NOT found in transcript - check"
        md.append(f"   - Evidence: \"{a.get('quote')}\" ({flag})")
        if a.get("review_note"):
            md.append(f"   - Note: {a['review_note']}")
    md.append("")

    meta = data.get("meta") or {}
    if meta:
        md.append("---")
        md.append(
            f"_Generated by: speech-to-text `{meta.get('speech_to_text_model')}`, "
            f"transcript refinement `{meta.get('refinement_model')}`, "
            f"documentation `{meta.get('documentation_model')}`._"
        )
        for warning in meta.get("warnings") or []:
            md.append(f"\n> Warning: {warning}")
    return "\n".join(md)


def save_outputs(raw_text, refined_text, record, markdown_doc, folder="outputs"):
    """Write the four downloadable files and return their paths."""
    os.makedirs(folder, exist_ok=True)
    paths = {
        "json": os.path.join(folder, "meeting_notes.json"),
        "markdown": os.path.join(folder, "meeting_notes.md"),
        "raw": os.path.join(folder, "raw_transcript.txt"),
        "refined": os.path.join(folder, "refined_transcript.txt"),
    }
    with open(paths["json"], "w", encoding="utf-8") as f:
        json.dump(record, f, indent=2, ensure_ascii=False)
    for key, text in (("markdown", markdown_doc), ("raw", raw_text), ("refined", refined_text)):
        with open(paths[key], "w", encoding="utf-8") as f:
            f.write(text)
    return paths
